version: '3.8'

services:
  db:
    image: mysql
    command: --secure-file-priv=""
    ports:
      - 3307:3307
    environment:
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT:-3307}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-0000}
      - MYSQL_USER=${MYSQL_USER:-dbmanager}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-0000}
    # volumes:
    #   - mysql:/var/lib/mysql
    #   - mysql_config:/etc/mysql
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE  https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
        
# volumes:
#     mysql:
#     mysql_config:
